# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

except:
    - docs

environment:

  matrix:
    - PYTHON: "C:\\Python27-conda32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-conda64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # install dependencies
  - "python -m pip install --upgrade pip"
  - "conda install --yes --quiet -c conda-forge geopandas matplotlib Pillow joblib netCDF4 scikit-image configobj nose pyproj numpy rasterio krb5 xarray"
  - "pip install git+https://github.com/fmaussion/motionless.git"
  - "pip install git+https://github.com/fmaussion/salem.git"
  - "pip install git+https://github.com/fmaussion/cleo.git"
  - "pip install -e ."

build: false

test_script:
  - "nosetests ."
