name: oggm
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.14.0rc1
  - scipy=1.0.1
  - gdal=2.2.3
  - matplotlib=2.2.2
  - pandas=0.22.0
  - geopandas=0.3.0
  - Pillow=5.0.0
  - netCDF4=1.3.1
  - scikit-image=0.13.1
  - configobj
  - pyproj=1.9.5.1
  - krb5
  - conda-forge/label/dev::rasterio
  - xarray=0.10.2
  - boto3
  - numpydoc
  - ipython=6.2.1
  - sphinx
  - pip:
    - motionless
    - git+https://github.com/fmaussion/salem.git
