name: oggm
channels:
  - conda-forge
dependencies:
  - python=3.5
  - numpy
  - scipy
  - gdal
  - matplotlib=1.5.3
  - pandas
  - geopandas
  - Pillow
  - joblib
  - netCDF4
  - scikit-image
  - configobj
  - pyproj
  - krb5
  - rasterio
  - xarray
  - filelock
  - numpydoc
  - ipython=4.0.3
  - sphinx=1.5
  - pip:
    - motionless
    - git+https://github.com/fmaussion/salem.git
