name: oggmdocs
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - shapely
  - matplotlib=3.0.3
  - Pillow
  - netcdf4
  - scikit-image
  - configobj
  - xarray
  - pytest
  - dask
  - bottleneck
  - pyproj
  - cartopy
  - geopandas
  - rasterio
  - descartes
  - seaborn
  - numpydoc
  - ipython
  - sphinx
  - pip
  - pip:
    - joblib
    - progressbar2
    - motionless
    - git+https://github.com/fmaussion/salem.git
    - git+https://github.com/OGGM/pytest-mpl
